source "https://rubygems.org"

gem "fastlane"
gem "spaceship", "~> 1.68"
gem "ios-certs"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
