title: RHYTHMIX Self-Hosted
theme: dark
color: slate
headerStyle: clean
layout:
  Productivity:
    style: row
    columns: 4
  Media & Knowledge:
    style: row
    columns: 4
  Developer:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 4
