- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: custom
    url: https://search.{{HOMEPAGE_VAR_DOMAIN}}/search?q=
    target: _blank

- greeting:
    text_size: xl
    text: RHYTHMIX Self-Hosted
