export const BUDDY_VIBES = {
  1: {
    name: "My Buddy",
    vibe: "warm, playful, energetic",
    primary: "#F5E6D3",
    secondary: "#FFE5B4",
    accent: "#FF8C42",
    textColor: "#2D2D2D",
    shadowStyle: "gentle",
    animationPace: "normal",
    fontSize: "base"
  },
  2: {
    name: "Anxiety Relief",
    vibe: "calm, warm, professional",
    primary: "#E0E7F1",
    secondary: "#C8D9E8",
    accent: "#7BA3B8",
    textColor: "#333333",
    shadowStyle: "gentle",
    animationPace: "slow",
    fontSize: "base"
  },
  3: {
    name: "Depression Buddy",
    vibe: "gentle, warm, nostalgic",
    primary: "#E8D5C4",
    secondary: "#D4C4B8",
    accent: "#C9A874",
    textColor: "#2D2D2D",
    shadowStyle: "gentle",
    animationPace: "slow",
    fontSize: "base"
  },
  4: {
    name: "Sleep Buddy",
    vibe: "soft, dreamy, slow",
    primary: "#E8D5F2",
    secondary: "#D5C8E8",
    accent: "#B8A8D5",
    textColor: "#2D2D2D",
    shadowStyle: "gentle",
    animationPace: "slow",
    fontSize: "base"
  },
  5: {
    name: "Grief Buddy",
    vibe: "tender, slow, compassionate",
    primary: "#D5E3F2",
    secondary: "#C8D9E8",
    accent: "#9FB3C8",
    textColor: "#333333",
    shadowStyle: "gentle",
    animationPace: "slow",
    fontSize: "base"
  },
  6: {
    name: "Elderly Companion",
    vibe: "gentle, warm, nostalgic",
    primary: "#E8D5C4",
    secondary: "#D4C4B8",
    accent: "#C9A874",
    textColor: "#2D2D2D",
    shadowStyle: "gentle",
    animationPace: "slow",
    fontSize: "large"
  },
  7: {
    name: "Parenting Coach",
    vibe: "warm, encouraging, down-to-earth",
    primary: "#F5E6D3",
    secondary: "#E8D5C4",
    accent: "#D4A574",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  8: {
    name: "Teen Mentor",
    vibe: "friendly, genuine, relaxed",
    primary: "#F5E6D3",
    secondary: "#FFE5B4",
    accent: "#FF8C42",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  9: {
    name: "Recovery Buddy",
    vibe: "steady, grounded, encouraging",
    primary: "#E0E7F1",
    secondary: "#C8D9E8",
    accent: "#7BA3B8",
    textColor: "#333333",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  10: {
    name: "Job Search Buddy",
    vibe: "upbeat, practical, motivating",
    primary: "#FFE5B4",
    secondary: "#FF8C42",
    accent: "#FF6B6B",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  11: {
    name: "Career Coach",
    vibe: "confident, warm, insightful",
    primary: "#F0F4F8",
    secondary: "#E8EEF5",
    accent: "#7BA3B8",
    textColor: "#333333",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  12: {
    name: "Study Buddy",
    vibe: "bright, encouraging, focused",
    primary: "#FFE5B4",
    secondary: "#FF8C42",
    accent: "#4ECDC4",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "fast",
    fontSize: "base"
  },
  13: {
    name: "Creative Partner",
    vibe: "playful, energetic, imaginative",
    primary: "#F5D5E0",
    secondary: "#FFE5B4",
    accent: "#FF6B6B",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  14: {
    name: "Startup Mentor",
    vibe: "energetic, direct, motivating",
    primary: "#F0F4F8",
    secondary: "#FF8C42",
    accent: "#FF6B6B",
    textColor: "#333333",
    shadowStyle: "moderate",
    animationPace: "fast",
    fontSize: "base"
  },
  15: {
    name: "Fitness Coach",
    vibe: "upbeat, motivating, bold",
    primary: "#FFB84D",
    secondary: "#FF8C42",
    accent: "#FF6B6B",
    textColor: "#F5F5F5",
    shadowStyle: "bold",
    animationPace: "fast",
    fontSize: "base"
  },
  16: {
    name: "Nutrition Buddy",
    vibe: "warm, gentle, reassuring",
    primary: "#F5E6D3",
    secondary: "#E8D5C4",
    accent: "#D4A574",
    textColor: "#2D2D2D",
    shadowStyle: "gentle",
    animationPace: "normal",
    fontSize: "base"
  },
  17: {
    name: "Travel Companion",
    vibe: "warm, adventurous, upbeat",
    primary: "#FFE5B4",
    secondary: "#FF8C42",
    accent: "#4ECDC4",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "fast",
    fontSize: "base"
  },
  18: {
    name: "Financial Coach",
    vibe: "calm, reassuring, clear",
    primary: "#E0E7F1",
    secondary: "#D5E3F2",
    accent: "#7BA3B8",
    textColor: "#333333",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  19: {
    name: "Hobby Explorer",
    vibe: "cheerful, curious, encouraging",
    primary: "#F5D5E0",
    secondary: "#FFE5B4",
    accent: "#FF8C42",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  20: {
    name: "Life Goals Coach",
    vibe: "inspiring, warm, grounded",
    primary: "#F5E6D3",
    secondary: "#E0E7F1",
    accent: "#7BA3B8",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  21: {
    name: "Anti-Bullying Buddy",
    vibe: "warm, protective, steady",
    primary: "#F5E6D3",
    secondary: "#E0E7F1",
    accent: "#7BA3B8",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  22: {
    name: "ADHD Buddy",
    vibe: "warm, energetic, validating",
    primary: "#F5E6D3",
    secondary: "#FFE5B4",
    accent: "#FF8C42",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "fast",
    fontSize: "base"
  },
  23: {
    name: "Autism Spectrum Buddy",
    vibe: "patient, understanding, detailed",
    primary: "#E0E7F1",
    secondary: "#C8D9E8",
    accent: "#7BA3B8",
    textColor: "#333333",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  24: {
    name: "Chronic Pain Buddy",
    vibe: "gentle, compassionate, accepting",
    primary: "#E8D5C4",
    secondary: "#D5C8E8",
    accent: "#B8A8D5",
    textColor: "#2D2D2D",
    shadowStyle: "gentle",
    animationPace: "slow",
    fontSize: "base"
  },
  25: {
    name: "Addiction Recovery Buddy",
    vibe: "warm, supportive, steadfast",
    primary: "#E8D5C4",
    secondary: "#E0E7F1",
    accent: "#7BA3B8",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  26: {
    name: "LGBTQ+ Ally Buddy",
    vibe: "warm, celebratory, affirming",
    primary: "#F5D5E0",
    secondary: "#FFE5B4",
    accent: "#FF6B6B",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  27: {
    name: "Disability Buddy",
    vibe: "warm, matter-of-fact, empowering",
    primary: "#F5E6D3",
    secondary: "#E0E7F1",
    accent: "#7BA3B8",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  28: {
    name: "Imposter Syndrome Buddy",
    vibe: "warm, confident, reassuring",
    primary: "#F5E6D3",
    secondary: "#E0E7F1",
    accent: "#7BA3B8",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  29: {
    name: "Dating & Romance Coach",
    vibe: "warm, playful, confident",
    primary: "#F5D5E0",
    secondary: "#FFE5B4",
    accent: "#FF8C42",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  30: {
    name: "New Relationship Buddy",
    vibe: "warm, uplifted, encouraging",
    primary: "#F5D5E0",
    secondary: "#FFE5B4",
    accent: "#FF6B6B",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  31: {
    name: "Breakup Recovery Buddy",
    vibe: "gentle, understanding, compassionate",
    primary: "#E8D5C4",
    secondary: "#D5E3F2",
    accent: "#9FB3C8",
    textColor: "#2D2D2D",
    shadowStyle: "gentle",
    animationPace: "slow",
    fontSize: "base"
  },
  32: {
    name: "Long-Distance Love Buddy",
    vibe: "warm, steady, reassuring",
    primary: "#F5E6D3",
    secondary: "#E0E7F1",
    accent: "#7BA3B8",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  33: {
    name: "Social Anxiety & Making Friends Coach",
    vibe: "warm, encouraging, patient",
    primary: "#F5E6D3",
    secondary: "#E0E7F1",
    accent: "#7BA3B8",
    textColor: "#2D2D2D",
    shadowStyle: "gentle",
    animationPace: "normal",
    fontSize: "base"
  },
  34: {
    name: "New City Companion",
    vibe: "upbeat, welcoming, adventurous",
    primary: "#FFE5B4",
    secondary: "#FF8C42",
    accent: "#4ECDC4",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "fast",
    fontSize: "base"
  },
  35: {
    name: "Workplace Friendship Coach",
    vibe: "warm, practical, understanding",
    primary: "#F5E6D3",
    secondary: "#E0E7F1",
    accent: "#7BA3B8",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  36: {
    name: "Meetup & Social Skills Coach",
    vibe: "encouraging, energetic, friendly",
    primary: "#FFE5B4",
    secondary: "#FF8C42",
    accent: "#FF6B6B",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "fast",
    fontSize: "base"
  },
  37: {
    name: "Solo Traveler Buddy",
    vibe: "adventurous, confident, upbeat",
    primary: "#FFE5B4",
    secondary: "#FF8C42",
    accent: "#4ECDC4",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "fast",
    fontSize: "base"
  },
  38: {
    name: "Self-Love & Solo Life Buddy",
    vibe: "warm, celebratory, empowering",
    primary: "#F5D5E0",
    secondary: "#FFE5B4",
    accent: "#FF6B6B",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  39: {
    name: "Burnout Recovery Buddy",
    vibe: "calm, restorative, compassionate",
    primary: "#D5E3F2",
    secondary: "#C8D9E8",
    accent: "#9FB3C8",
    textColor: "#333333",
    shadowStyle: "gentle",
    animationPace: "slow",
    fontSize: "base"
  },
  40: {
    name: "Executive Stress Coach",
    vibe: "professional, calm, strategic",
    primary: "#F0F4F8",
    secondary: "#E8EEF5",
    accent: "#7BA3B8",
    textColor: "#333333",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  41: {
    name: "Work-Life Balance Buddy",
    vibe: "balanced, warm, clear",
    primary: "#F5E6D3",
    secondary: "#E0E7F1",
    accent: "#7BA3B8",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  42: {
    name: "Sleep Optimization Coach",
    vibe: "soft, dreamy, slow",
    primary: "#E8D5F2",
    secondary: "#D5C8E8",
    accent: "#B8A8D5",
    textColor: "#2D2D2D",
    shadowStyle: "gentle",
    animationPace: "slow",
    fontSize: "base"
  },
  43: {
    name: "Recovery & Wellness Buddy",
    vibe: "warm, supportive, holistic",
    primary: "#F5E6D3",
    secondary: "#E0E7F1",
    accent: "#7BA3B8",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  44: {
    name: "Deep Work & Focus Coach",
    vibe: "calm, focused, motivating",
    primary: "#E0E7F1",
    secondary: "#C8D9E8",
    accent: "#7BA3B8",
    textColor: "#333333",
    shadowStyle: "moderate",
    animationPace: "slow",
    fontSize: "base"
  },
  45: {
    name: "Executive Performance Coach",
    vibe: "professional, confident, strategic",
    primary: "#F0F4F8",
    secondary: "#E8EEF5",
    accent: "#7BA3B8",
    textColor: "#333333",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  46: {
    name: "Remote Work Isolation Buddy",
    vibe: "warm, connecting, upbeat",
    primary: "#F5E6D3",
    secondary: "#FFE5B4",
    accent: "#FF8C42",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  47: {
    name: "Nutrition & Meal Planning Buddy",
    vibe: "warm, practical, encouraging",
    primary: "#F5E6D3",
    secondary: "#E8D5C4",
    accent: "#D4A574",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  48: {
    name: "Meditation & Mindfulness Studio",
    vibe: "calm, serene, peaceful",
    primary: "#D5E3F2",
    secondary: "#C8D9E8",
    accent: "#9FB3C8",
    textColor: "#333333",
    shadowStyle: "gentle",
    animationPace: "slow",
    fontSize: "base"
  },
  49: {
    name: "Healthy Habits Accountability Buddy",
    vibe: "warm, supportive, motivating",
    primary: "#F5E6D3",
    secondary: "#FFE5B4",
    accent: "#FF8C42",
    textColor: "#2D2D2D",
    shadowStyle: "moderate",
    animationPace: "normal",
    fontSize: "base"
  },
  50: {
    name: "Mental Resilience Trainer",
    vibe: "strong, confident, empowering",
    primary: "#F0F4F8",
    secondary: "#FFB84D",
    accent: "#FF6B6B",
    textColor: "#333333",
    shadowStyle: "bold",
    animationPace: "normal",
    fontSize: "base"
  }
};
